CREATE TABLE lessons (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  course_id BIGINT REFERENCES courses (id),
  name_lesson VARCHAR(300) NOT NULL,
  description_lesson TEXT,
  video_link VARCHAR(500) NOT NULL,
  position_lesson INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  link_course VARCHAR(500) NOT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE courses (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name_course VARCHAR(300) NOT NULL,
  description_course TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE modules (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name_module VARCHAR(250) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE module_course (
  module_id BIGINT REFERENCES modules (id),
  course_id BIGINT REFERENCES courses (id),
  PRIMARY KEY (module_id, course_id)
)

CREATE TABLE programs (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name_program VARCHAR(350) NOT NULL,
  price INT NOT NULL,
  type_program VARCHAR(350) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE program_module (
  program_id BIGINT REFERENCES programs (id),
  module_id BIGINT REFERENCES modules (id),
  PRIMARY KEY (program_id, module_id)
);
